### PR TITLE
Support ID scalar better

### PR DESCRIPTION
**Pull request by newhouse**
Addresses https://github.com/charlypoly/graphql-to-json-schema/issues/38

### CODE REVIEW

**Comment by newhouse** [comment]
bump @charlypoly

**Review by charlypoly — APPROVED** [review]
LGTM @newhouse, thanks!

Let me find some time to publish it in a new release soon.

**Comment by newhouse** [comment]
> LGTM @newhouse, thanks!
> 
> 
> 
> Let me find some time to publish it in a new release soon.

Ok @charlypoly all merged up. Let me know when it's been released. Thanks!

**Comment by charlypoly** [comment]
@newhouse released in `graphql-2-json-schema@0.10.0`

**Pull request merged**
