### PR TITLE
feat: support interface and union

### PR DESCRIPTION
**Pull request by aldeed**
## Changes

Adds support for GraphQL interfaces, output in `definitions` the same as object types:

```js
{
  type: 'object',
  description: 'Anything with an ID can be a node',
  properties: {
    id: { type: 'string', description: 'A unique identifier' }
  },
  required: ['id']
}
```

Adds support for GraphQL unions, output in `definitions` as objects with anyOf refs:

```js
{
  type: 'object',
  description: 'Example union',
  anyOf: [
    { $ref: '#/definitions/Todo' }
  ]
}
```

Adds support for GraphQL custom scalars, output in `definitions` as string fields:

```js
{
  type: 'string',
  description: 'A custom scalar'
}
```

Updates `typesMapping.ts` to use refs for anything that isn't a built-in scalar, so that the new definitions above are properly referenced.

Updates `typesMapping.ts` to map `Int` to `integer` instead of `number`. This could be reverted if there was some good reason for not using `integer`.

Updates the test to verify all of these changes work.

## Question

Assuming all custom scalars map down to "string" is a good default but will not always be correct. I don't think scalar definitions have any discrete properties that identify what built-in scalar they map to. For example `JSONObject` is a common one that should map to an object with any keys allowed. Or something like `PositiveInt` should map to `integer`.

Two possible ways to get the info:
- A mapping of custom scalar name to built-in scalar name could be passed into `fromIntrospectionQuery` options.
- Invent a directive to put on the scalar in the schema, like `@customScalar(builtInType: "Int")`

### CODE REVIEW

**Comment by aldeed** [comment]
@wittydeveloper I rebased this on 0.2, which implemented similar support for scalars. I think assuming `object` for non-built-in scalars isn't as good as assuming `string` (if it's an object, it wouldn't be defined as a scalar), but since neither is a great solution, I'll roll with it.

So this now adds support for interfaces and unions, and fixes the test so it is passing. Can this be merged and released?

(I would still like to add support for `@customScalar(builtInType: "Int")` directive in a future PR if you think that's a good idea. We are using this to generate docs and it's misleading for it to say "object" for something that is really a string.)

**Comment by songleng** [comment]
Is there a plan on adding the interface and union support?  This PR has been open for a while

**Comment by aldeed** [comment]
If anyone plans to merge this, I could rebase and fix conflicts.

**Comment by trevorr** [comment]
@charlypoly Could this be merged if the conflicts are fixed? I think it's blocking interface support in SpectaQL (https://github.com/anvilco/spectaql/issues/92).

**Comment by bmanturner** [comment]
Let's get this in

**Comment by charlypoly** [comment]
Hi all!

@aldeed, thank you for the patch proposal, would you still be open to fix the conflicts?

Otherwise, LGTM for merge ASAP 🚢

**Comment by newhouse** [comment]
I have opened another PR that does just the `INTERFACE` stuff, as I think the `UNION` and `SCALAR` stuff is already "in there"™️ .

**Comment by newhouse** [comment]
> I have opened another PR that does just the `INTERFACE` stuff, as I think the `UNION` and `SCALAR` stuff is already "in there"™️ .

In the meantime, if you really, really want this dependency with the fix, you can use the version I've published here: https://www.npmjs.com/package/@anvilco/graphql-2-json-schema

Version `0.0.3` should have it. It's running latest [`anvil-master`](https://github.com/anvilco/graphql-to-json-schema/tree/anvil-master) branch.

**Comment by charlypoly** [comment]
Both unions and interface are available in `graphql-2-json-schema@0.8.0`

**Pull request closed without merging**
